# Generated by Django 4.1.4 on 2022-12-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pagos_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
